name: Build and Test Backend (CMW)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
      
      - name: Run basic test
        run: |
          echo "✅ Environment loaded successfully"
          echo "PORT=$PORT"
          echo "MONGODB_URI=$MONGODB_URI"
          echo "JWT_SECRET=$JWT_SECRET"

